### PR TITLE
feat: allow custom Project Names

### PR DESCRIPTION
**Pull request by adityastic**
Fixes issue #28 

Changes: 
- Added Another Field Named Project Name to help people enter their project

Screenshots for the change:
Screenshot 2019-06-07 at 2 52 45 PM

### CODE REVIEW

**Comment by adityastic** [comment]
@mariobehling this might be helpful for some people

**Comment by mariobehling** [comment]
Please resolve Travis errors.

**Comment by adityastic** [comment]
@mariobehling updated

**Comment by hkedia321** [comment]
@adityastic Why did you delete `scripts/background.js` file? The extension doesn't load without it. Please fix this.
image

**Comment by mariobehling** [comment]
Ok, that was my mistake as well. Did not check carefully enough. Thanks for quickly pointing this out! I am reverting it.

**Comment by mariobehling** [comment]
@adityastic Please create a new PR taking care of this issue. Thanks.

**Comment by adityastic** [comment]
@mariobehling on it

**Pull request merged**
