### PR TITLE
fix the date interval in the scrumHelper (Fixes#36)

### PR DESCRIPTION
**Pull request by Harshdev098**
Fixes issue #36 

Changes: [Add here what changes were made in this issue and if possible provide links.]
changed the date interval code in scrumHelper file, now it will show what I did in last 4 days or last 7 days or from Date X to Date y

Screenshots for the change:

### CODE REVIEW

**Comment by Harshdev098** [comment]
@mariobehling  @hpdang    I've made a PR. Please take a moment to review it

**Comment by mariobehling** [comment]
Please provide a sample screenshot for the change.

**Comment by Harshdev098** [comment]
Now, its showing the correct interval dates as mentioned in the issue

Screenshot 2024-03-02 142412

**Comment by mariobehling** [comment]
The project is used by different people around the world. In particular if dates are single digit some people might get confused as there are different date formats used in different regions. Therefore use a format that is easily understood everywhere. Please change the format like 2024-02-24 to 24 Feb 2024. Thanks

**Comment by Harshdev098** [comment]
updated the date format


Screenshot 2024-03-02 160904

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
